
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "BOOL FILESTRING LITSTRING NAME OPCONST OPDEFINE OPNORM OPTION STOPWORDstatement : statement : NAME OPCONST stringstatement : NAME OPDEFINEstatement : OPTION NAME BOOLstatement : STOPWORD strliststrlist : string ',' strlist\n                | string strlist\n                | statement : OPNORMstring : LITSTRING\n              | FILESTRING"
    
_lr_action_items = {'$end':([0,1,4,5,7,9,10,11,12,13,14,15,16,17,],[-1,0,-8,-9,-3,-5,-8,-10,-11,-2,-4,-8,-7,-6,]),'NAME':([0,3,],[2,8,]),'OPTION':([0,],[3,]),'STOPWORD':([0,],[4,]),'OPNORM':([0,],[5,]),'OPCONST':([2,],[6,]),'OPDEFINE':([2,],[7,]),'LITSTRING':([4,6,10,11,12,15,],[11,11,11,-10,-11,11,]),'FILESTRING':([4,6,10,11,12,15,],[12,12,12,-10,-11,12,]),'BOOL':([8,],[14,]),',':([10,11,12,],[15,-10,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'strlist':([4,10,15,],[9,16,17,]),'string':([4,6,10,15,],[10,13,10,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> <empty>','statement',0,'p_statement_empty','plex.py',82),
  ('statement -> NAME OPCONST string','statement',3,'p_statement_define_constant','plex.py',86),
  ('statement -> NAME OPDEFINE','statement',2,'p_statement_define_rule','plex.py',103),
  ('statement -> OPTION NAME BOOL','statement',3,'p_statement_option','plex.py',121),
  ('statement -> STOPWORD strlist','statement',2,'p_statement_stopword','plex.py',134),
  ('strlist -> string , strlist','strlist',3,'p_expression_strlist','plex.py',139),
  ('strlist -> string strlist','strlist',2,'p_expression_strlist','plex.py',140),
  ('strlist -> <empty>','strlist',0,'p_expression_strlist','plex.py',141),
  ('statement -> OPNORM','statement',1,'p_statement_normalise','plex.py',167),
  ('string -> LITSTRING','string',1,'p_expression_string','plex.py',248),
  ('string -> FILESTRING','string',1,'p_expression_string','plex.py',249),
]
